### ISSUE TITLE
Creative Commons License

### ISSUE THREAD

**Issue by elioqoshi** [oliverpitsch/apple-product-icons#5]
Thanks a lot for these icons!
What bothers me is that you haven't specified a license when you kindly ask us to give attribution to you.
Why not release the icons under a Creative Commons Attribution license?

**Comment by oliverpitsch** [comment]
You are absolutely right. I'll change that asap. I'll go with the Attribution-NonCommercial-ShareAlike 4.0 International license. http://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by elioqoshi** [comment]
@oliverpitsch Why NonCommercial? obviously a lot want to use this also for projects which are not non profit? You sure about this? ( I mean the fact it's about Apple makes it pretty much commercial)
Thanks a lot again!

**Comment by oliverpitsch** [comment]
@elioqoshi I don't own any rights on the shown products. They are all the property of Apple. That's why I can not allow a commercial use without asking Apple. But you may of course ask Apple and use the icons afterwards. ;) For me it would be absolutely okay.

**Comment by elioqoshi** [comment]
This is your creation, Apple doesn't own it, even if you are depicting them. With that logic even a not commercial use wouldn't be allowed :)
